index.html, style.css
I have fixed this explore button problem 
I have add css and also made some changes in html file
=> fixed explore button problem

css/style.css, index.html, js/script.js
This update addresses a bug where the Roadmap button was not functioning correctly. The issue has been resolved, ensuring that the button operates as intended. Additionally, a new styling feature has been implemented: when the button is active, it will turn white with black text, providing a clear visual indication of its state. This improvement enhances the user experience by making the active button more distinguishable.
This is PR of issuse #1
=> Fix for Roadmap Button Functionality and Styling 

css/sidebar.css, css/yatu_learn_aiml.html, index.html, pages/construction.html, pages/privacy_learn.html, pages/yatu_learn_about.html, pages/yatu_learn_aiml.html, pages/yatu_learn_cn.html, pages/yatu_learn_cs.html, pages/yatu_learn_dsa.html, pages/yatu_learn_notes.html, pages/yatu_learn_os.html, pages/yatu_learn_qp.html, pages/yatu_learn_wd.html
I have updated the side scrollbar in all the pages and make user attractive and compact and theme matched.
Issue #71 Completed
and also in every HTML page.
=> Update Scrollbar | Issue #71

README.md
I have added the script to add all contributors in the readme.md file, to give them as a token of appreciation for their hard work.
Completed #66
=> Additon of All Contributors Photos | Issue 66

css/yatu_learn_notes.css, js/yatu_learn_script.js, pages/yatu_learn_notes.html
I have created the subsections in notes page. These subsections are based on Branch, Subjects or Technology. We can add or modify it in future. The subsections are collapsible providing efficient user interface and beginner friendly.
I have attached the screenshots for reference.
Please accept it under gssoc-ext level-3 and hacktoberfest.
=> PR for [Enhancement] Adding subsections in Notes page - issue #19

css/style.css, index.html
<h2>Added on hover color change feature to the social icons in the footer section</h2>
Issue no --> #84 
changed each social icon to their primary color when user hover over it ,like:
- Facebook:blue
- Instagram:pink
- linkedin-blue
<h1>Before</h1>:
https://github.com/user-attachments/assets/dfbc97f7-6ae0-4413-93ea-7cf737b159af
<h1>yatu After</h1>:
https://github.com/user-attachments/assets/64692a89-2965-4ae7-af16-5cb7bb20279c
=> added on-hover-color change feature to Social Icons.

css/style.css, index.html
Question paper button which was terning black and we were unable to see it when we hover it is now corrected
https://github.com/user-attachments/assets/7146786a-3000-479c-bfd3-02f9d03a3de4
=> Question paper button hover corrected #115

index.html
hover issue #114 is now resolved and it is working properly 
https://github.com/user-attachments/assets/9a900b30-5dd8-4b48-ad97-2baa4a1a3089
=> web development hover is corrected now

css/yatu_learn_dsa.css, pages/yatu_learn_dsa.html
I Have fixed the misalignment of the content of paragraphs and also updated the content of paragraphs (where needed).
Added bullet points that showcase the UX for better interaction.
Update the Title alignment of the page.
Also, I refactored the CSS file that contains duplicate/repetitive code
https://github.com/user-attachments/assets/0ff8972a-98eb-4e7c-a9ea-d9a603754704
=> Update the DSA Page | #87

css/yatu_learn_notes.css, pages/yatu_learn_notes.html
=> Added search bar according to new notes page

pages/yatu_learn_aiml.html, pages/yatu_learn_cn.html, pages/yatu_learn_cs.html, pages/yatu_learn_dsa.html, pages/yatu_learn_os.html, pages/yatu_learn_wd.html
Adding the reference link for notes related to that field. #78 
There are not so much notes available for each of the course that's why i added the recomended resources so that people who wants to learn they can learn through these resources and help them grow.
I have added recomended resourses for all 6 courses on the website.
@yatulearn Check the changes and merge it then.
=> Added the recomended resources section in all the courses

index.html, pages/construction.html, pages/privacy_learn.html, pages/yatu_learn_about.html, pages/yatu_learn_aiml.html, pages/yatu_learn_cn.html, pages/yatu_learn_cs.html, pages/yatu_learn_dsa.html, pages/yatu_learn_notes.html, pages/yatu_learn_os.html, pages/yatu_learn_qp.html, pages/yatu_learn_wd.html, yatu_learn_aiml.html, yatu_learn_cn.html, yatu_learn_cs.html, yatu_learn_dsa.html, yatu_learn_os.html, yatu_learn_wd.html
Fix #156 
- Add Favicon in All the HTML Pages
- Please accept the Pull Request under Hacktoberfest or Hacktoberfest2024
=> Add Favicon in All the HTML Pages

js/script.js
Here is an overview of what changes I have made
1. change "var" to "const" at required places
2. change scrollToTop and scrollUpLinks format to enhance readability and reduce load time 
3. Made a small changes on buttons.forEach() 
(Images are enclosed below for the changes)
The rest of the code was all perfect !! You are doing a great job!!! Thank you for allowing me to make these small changes
Thanks,
Yash Vashishth
(Contributor- GSSOC-EXT 2024)
**( P.S. ) :-** Please add the hacktoberfest and gssoc-ext tags on this pull request too
=> Necessary changes to improve code quality

css/yatu_learn_about.css, pages/yatu_learn_about.html
@yatulearn I have updated the code, and fixes the conflicts.
Issue #46 Completed.
https://github.com/user-attachments/assets/a70969a4-d43b-481f-bf24-8a85d2746816
=> Updation of AboutUs Page with Responsiveness | Issue #46

pages/yatu_learn_os.html, pages/yatu_learn_qp.html, pages/yatu_learn_wd.html
Fixes #134 
Please add the GSSoC Extended and Hactoberfest labels to this PR
=> Fixes #134

LICENSE.txt
=> #165 Added LICENSE File in Root Directory

README.md
Fixed the issue of duplicate sections in `README.md` by removing the repeated `License` and `Our Valuable Contributors` sections, ensuring these sections only appear once in the document.
- Closes #208 
N/A
This PR resolves the issue of duplicate `License` and `Our Valuable Contributors` sections in the `README.md`, improving the overall structure and readability of the file. #208
=> Update README.md #208

css/style.css, index.html
1. Fix Navbar issue in Mobile and Tablet size.
2. Give spacing between the navbar options for screens larger than the tablet size.
3. Give proper padding in the drop down navbar option.
4. give proper margin in the hemburger bar for mobile screen and in navbar .
5. Give proper position to the hemburger bar
Issue Number #184 
Pls assign label gssoc-ext , hacktoberfest-accepted, level2
=> Fix The NavBar Issue

index.html
Hello PA,
I have corrected spelling  of 'Web Development'.
=> spelling corrected

Dockerfile, README.md
=> Added Dockerfile for containerization and Update README for Containerization

css/B2T.css, css/style.css, index.html, js/B2T.js, pages/privacy_learn.html, pages/yatu_learn_about.html, pages/yatu_learn_aiml.html, pages/yatu_learn_cn.html, pages/yatu_learn_cs.html, pages/yatu_learn_dsa.html, pages/yatu_learn_notes.html, pages/yatu_learn_os.html, pages/yatu_learn_qp.html, pages/yatu_learn_wd.html
Completed #70 
https://github.com/user-attachments/assets/904a97b8-71ad-4e88-af07-dab02d6e6562
Please review, and merge
I have added BackToTop Button in all the pages, could u please increase the level of this issue for this PR.
=> Addition of B2T | Issue #70

pages/yatu_learn_qp.html
Completed #118 
https://github.com/user-attachments/assets/168965e8-212c-415b-924c-9460a851f239
@yatulearn please review and close issue #118 with the exact label of level that is proposed by you in the issue.
=> Updation of Questions Papers UI | Issue #118

css/yatu_learn_about.css, js/FAQs.js, pages/yatu_learn_about.html
Completed #88 
https://github.com/user-attachments/assets/f046f82a-59cc-4a3e-8357-a22456279e0e
@yatulearn please check, and merge
=> Addition of FAQs | Issue #88

css/yatu_learn_about.css, pages/yatu_learn_about.html
Enhanced the alignment of Contact Us part on About page which makes it more attractive.
Fixes #155 
@yatulearn Plz accept it under gssoc-ext level1 and hacktoberfest
=> Fix alignment on About page

css/style.css
Hi @yatulearn 
This PR enhances the user experience by:
- Providing a more visually appealing page load with a smooth fade-in and scale effect, making the content appear more polished.
- Adding a subtle hover effect that encourages interaction without being too aggressive, enhancing user engagement.
These changes improve the overall look and feel of the site, creating a more professional and interactive user experience.
**Kindly MERGE this and assign me the level.**
fixes: #269 
Thank you :)
=> Added smooth image load-in animation with subtle hover effect

css/style.css, js/script.js, pages/yatu_learn_about.html
I have improved the positioning of the 'Back to Top' button, which was previously hidden behind another button, ensuring it's now fully visible and accessible. Additionally, I've added some underlines to enhance the visual appeal. I am committed to continuously improving this project, so I kindly request that you accept my pull request.
=> STYLE IMPROVED

css/style.css, js/script.js, pages/yatu_learn_about.html
Reverts yatulearn/yatulearn#463
=> Revert "STYLE IMPROVED"

css/style.css
Reverts yatulearn/yatulearn#312
=> Revert "Added smooth image load-in animation with subtle hover effect"

css/yatu_learn_about.css, pages/yatu_learn_about.html
Reverts yatulearn/yatulearn#222
=> Revert "Fix alignment on About page"
